// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	audit "url-shortener/internal/audit"

	mock "github.com/stretchr/testify/mock"
)

// Sink is an autogenerated mock type for the Sink type
type Sink struct {
	mock.Mock
}

type Sink_Expecter struct {
	mock *mock.Mock
}

func (_m *Sink) EXPECT() *Sink_Expecter {
	return &Sink_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Sink) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sink_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Sink_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Sink_Expecter) Close() *Sink_Close_Call {
	return &Sink_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Sink_Close_Call) Run(run func()) *Sink_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Sink_Close_Call) Return(_a0 error) *Sink_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Sink_Close_Call) RunAndReturn(run func() error) *Sink_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function with given fields: ctx, e
func (_m *Sink) Consume(ctx context.Context, e audit.Event) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, audit.Event) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sink_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type Sink_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - e audit.Event
func (_e *Sink_Expecter) Consume(ctx interface{}, e interface{}) *Sink_Consume_Call {
	return &Sink_Consume_Call{Call: _e.mock.On("Consume", ctx, e)}
}

func (_c *Sink_Consume_Call) Run(run func(ctx context.Context, e audit.Event)) *Sink_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(audit.Event))
	})
	return _c
}

func (_c *Sink_Consume_Call) Return(_a0 error) *Sink_Consume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Sink_Consume_Call) RunAndReturn(run func(context.Context, audit.Event) error) *Sink_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// NewSink creates a new instance of Sink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sink {
	mock := &Sink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
