// Code generated by cmd/reset; DO NOT EDIT.

package model

func (x *BatchRequest) Reset() {
	if x == nil {
		return
	}

	x.CorrelationID = ""
	x.OriginalURL = ""
}

func (x *BatchResponse) Reset() {
	if x == nil {
		return
	}

	x.CorrelationID = ""
	x.ShortURL = ""
}

func (x *ShortenRequest) Reset() {
	if x == nil {
		return
	}

	x.URL = ""
}

func (x *ShortenResponse) Reset() {
	if x == nil {
		return
	}

	x.Result = ""
}

func (x *URL) Reset() {
	if x == nil {
		return
	}

	x.ID = ""
	x.Original = ""
	x.Short = ""
	x.UserID = ""
	x.IsDeleted = false
}

func (x *UserURLResponse) Reset() {
	if x == nil {
		return
	}

	x.ShortURL = ""
	x.OriginalURL = ""
}
