package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestResetGenerator_GeneratesResetMethodsAndImports(t *testing.T) {
	tmp := t.TempDir()

	// cwd = tmp, потому что run() использует packages.Config{Dir:"."}
	oldwd, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() { _ = os.Chdir(oldwd) })

	writeGoMod(t, "example.com/test")

	writeFile(t, "b/b.go", strings.TrimSpace(`
package b

type Action string
`)+"\n")

	writeFile(t, "a/a.go", strings.TrimSpace(`
package a

import "example.com/test/b"

// generate:reset
type Resettable struct {
	I     int
	S     string
	Sl    []int
	M     map[string]int
	P     *string
	Act   b.Action
	Child *Child
}

type NotMarked struct {
	X int
}

type Child struct {
	N int
}

func (c *Child) Reset() {
	if c == nil { return }
	c.N = 0
}
`)+"\n")

	require.NoError(t, run())

	genPath := filepath.Join(tmp, "a", "reset.gen.go")
	bs, err := os.ReadFile(genPath)
	require.NoError(t, err)
	out := string(bs)

	require.Contains(t, out, "// Code generated by cmd/reset; DO NOT EDIT.")
	require.Contains(t, out, "package a")

	// импорт на внешний пакет
	require.Contains(t, out, "import (")
	require.Contains(t, out, "\t\"example.com/test/b\"")

	// метод Reset
	require.Contains(t, out, "func (x *Resettable) Reset() {")
	require.Contains(t, out, "if x == nil {")
	require.Contains(t, out, "return")

	// примитивы
	require.Contains(t, out, "x.I = 0")
	require.Contains(t, out, `x.S = ""`)

	// slice
	require.Contains(t, out, "x.Sl = x.Sl[:0]")

	// map
	require.Contains(t, out, "clear(x.M)")

	// pointer на string
	require.Contains(t, out, "if x.P != nil {")
	require.Contains(t, out, `*x.P = ""`)

	// внешний named type
	require.Contains(t, out, `x.Act = b.Action("")`)
	require.NotContains(t, out, "url-shortener/") // защита от старого бага

	// вложенный Reset()
	require.Contains(t, out, "x.Child.Reset()")

	// NotMarked не должен попасть
	require.NotContains(t, out, "func (x *NotMarked) Reset()")

	// пакет b не должен получить reset.gen.go
	_, err = os.Stat(filepath.Join(tmp, "b", "reset.gen.go"))
	require.Error(t, err)
	require.True(t, os.IsNotExist(err))
}

func TestResetGenerator_MarkerOnTypeSpecDocAlsoWorks(t *testing.T) {
	tmp := t.TempDir()

	oldwd, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() { _ = os.Chdir(oldwd) })

	writeGoMod(t, "example.com/test2")

	writeFile(t, "p/p.go", strings.TrimSpace(`
package p

type A int

// generate:reset
type OnlyThis struct {
	V A
}
`)+"\n")

	require.NoError(t, run())

	genPath := filepath.Join(tmp, "p", "reset.gen.go")
	bs, err := os.ReadFile(genPath)
	require.NoError(t, err)

	out := string(bs)
	require.Contains(t, out, "package p")
	require.Contains(t, out, "func (x *OnlyThis) Reset() {")
	require.Contains(t, out, "x.V = A(0)")
}

func TestResetGenerator_SkipsAlreadyGeneratedFiles(t *testing.T) {
	tmp := t.TempDir()

	oldwd, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(tmp))
	t.Cleanup(func() { _ = os.Chdir(oldwd) })

	writeGoMod(t, "example.com/test3")

	writeFile(t, "p/p.go", strings.TrimSpace(`
package p

// generate:reset
type X struct { A int }
`)+"\n")

	require.NoError(t, run())
	require.NoError(t, run())

	_, err = os.Stat(filepath.Join(tmp, "p", "reset.gen.go"))
	require.NoError(t, err)
}

func writeGoMod(t *testing.T, modulePath string) {
	t.Helper()

	// runtime.Version(): "go1.24.13", "go1.25.0", "devel go1.25-..." и т.п.
	v := runtime.Version()
	goLine := "1.24" // безопасный дефолт

	if strings.HasPrefix(v, "go1.") {
		rest := strings.TrimPrefix(v, "go")
		// rest = "1.24.13" / "1.25.0" / "1.25rc1" ...
		parts := strings.Split(rest, ".")
		if len(parts) >= 2 {
			minor := parts[1]
			// отрезаем всё после цифр (rc/beta и т.п.)
			minorDigits := minor
			for i := 0; i < len(minorDigits); i++ {
				if minorDigits[i] < '0' || minorDigits[i] > '9' {
					minorDigits = minorDigits[:i]
					break
				}
			}
			if minorDigits != "" {
				goLine = parts[0] + "." + minorDigits
			}
		}
	}

	writeFile(t, "go.mod", "module "+modulePath+"\n\ngo "+goLine+"\n")
}

func writeFile(t *testing.T, rel string, content string) {
	t.Helper()

	path := filepath.Join(".", filepath.FromSlash(rel))
	dir := filepath.Dir(path)
	require.NoError(t, os.MkdirAll(dir, 0o755))
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}
