package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const marker = "generate:reset"

func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, "reset generator error:", err)
	}
}

func run() error {
	cfg := &packages.Config{
		Dir: ".",
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return fmt.Errorf("load packages: %w", err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		return errors.New("package load errors")
	}

	resetIface := types.NewInterfaceType([]*types.Func{
		types.NewFunc(token.NoPos, nil, "Reset",
			types.NewSignatureType(nil, nil, nil, nil, nil, false),
		),
	}, nil).Complete()

	for _, pkg := range pkgs {
		if len(pkg.GoFiles) == 0 || len(pkg.Syntax) == 0 {
			continue
		}

		structs := findResetStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		out, err := generateForPackage(pkg, structs, resetIface)
		if err != nil {
			return fmt.Errorf("generate %s: %w", pkg.PkgPath, err)
		}

		dir := filepath.Dir(pkg.GoFiles[0])
		outPath := filepath.Join(dir, "reset.gen.go")
		if err := os.WriteFile(outPath, out, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", outPath, err)
		}
	}

	return nil
}

type resetStruct struct {
	Name   string
	Fields []resetField
}

type resetField struct {
	Name string
	Type types.Type
}

func findResetStructs(pkg *packages.Package) []resetStruct {
	byName := map[string]resetStruct{}

	for _, f := range pkg.Syntax {
		pos := pkg.Fset.Position(f.Pos())
		if strings.HasSuffix(pos.Filename, "reset.gen.go") {
			continue
		}

		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			blockHas := hasMarker(gd.Doc)

			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if !blockHas && !hasMarker(ts.Doc) {
					continue
				}

				_, ok = ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				obj := pkg.TypesInfo.Defs[ts.Name]
				tname, ok := obj.(*types.TypeName)
				if !ok {
					continue
				}
				named, ok := tname.Type().(*types.Named)
				if !ok {
					continue
				}
				st, ok := named.Underlying().(*types.Struct)
				if !ok {
					continue
				}

				fields := make([]resetField, 0, st.NumFields())
				for i := 0; i < st.NumFields(); i++ {
					fv := st.Field(i)

					fields = append(fields, resetField{
						Name: fv.Name(),
						Type: fv.Type(),
					})
				}

				byName[tname.Name()] = resetStruct{
					Name:   tname.Name(),
					Fields: fields,
				}
			}
		}
	}

	out := make([]resetStruct, 0, len(byName))
	for _, s := range byName {
		out = append(out, s)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func hasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		txt := strings.TrimSpace(c.Text)
		txt = strings.TrimPrefix(txt, "//")
		txt = strings.TrimSpace(strings.TrimPrefix(txt, "/*"))
		txt = strings.TrimSpace(strings.TrimSuffix(txt, "*/"))
		if strings.Contains(txt, marker) {
			return true
		}
	}
	return false
}

func generateForPackage(pkg *packages.Package, structs []resetStruct, resetIface *types.Interface) ([]byte, error) {
	imports := map[string]string{}
	usedAliases := map[string]bool{}

	qual := func(p *types.Package) string {
		if p == nil {
			return ""
		}
		if pkg.Types != nil && p.Path() == pkg.Types.Path() {
			return ""
		}
		return ensureImport(imports, usedAliases, p.Path(), p.Name())
	}

	var body bytes.Buffer
	for _, s := range structs {
		genResetMethod(&body, pkg, s, resetIface, qual)
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by cmd/reset; DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n", pkg.Name)
	fmt.Fprintln(&buf)

	if len(imports) > 0 {
		fmt.Fprintln(&buf, "import (")
		paths := make([]string, 0, len(imports))
		for p := range imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			al := imports[p]
			if al == "" {
				fmt.Fprintf(&buf, "\t%q\n", p)
			} else {
				fmt.Fprintf(&buf, "\t%s %q\n", al, p)
			}
		}
		fmt.Fprintln(&buf, ")")
		fmt.Fprintln(&buf)
	}

	buf.Write(body.Bytes())

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format: %w\n---\n%s\n---", err, buf.String())
	}
	return out, nil
}

func genResetMethod(
	out *bytes.Buffer,
	pkg *packages.Package,
	s resetStruct,
	resetIface *types.Interface,
	typeQual func(*types.Package) string,
) {
	recv := "x"
	fmt.Fprintf(out, "func (%s *%s) Reset() {\n", recv, s.Name)
	fmt.Fprintf(out, "\tif %s == nil {\n\t\treturn\n\t}\n\n", recv)

	for _, f := range s.Fields {
		for _, st := range genFieldResetStmts(recv+"."+f.Name, f.Type, resetIface, typeQual) {
			fmt.Fprintf(out, "\t%s\n", st)
		}
	}

	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func genFieldResetStmts(
	expr string,
	t types.Type,
	resetIface *types.Interface,
	typeQual func(*types.Package) string,
) []string {
	if types.Implements(t, resetIface) {
		return []string{fmt.Sprintf("%s.Reset()", expr)}
	}

	if types.Implements(types.NewPointer(t), resetIface) {
		return []string{fmt.Sprintf("(&%s).Reset()", expr)}
	}

	switch tt := t.(type) {
	case *types.Pointer:
		inner := genDerefReset(expr, tt.Elem(), resetIface, typeQual)
		if len(inner) == 0 {
			return nil
		}
		res := []string{fmt.Sprintf("if %s != nil {", expr)}
		for _, st := range inner {
			res = append(res, "\t"+st)
		}
		res = append(res, "}")
		return res

	case *types.Slice:
		return []string{fmt.Sprintf("%s = %s[:0]", expr, expr)}

	case *types.Map:
		return []string{fmt.Sprintf("clear(%s)", expr)}

	default:
		z := zeroValueExpr(t, typeQual)
		if z == "" {
			return nil
		}
		return []string{fmt.Sprintf("%s = %s", expr, z)}
	}
}

func genDerefReset(
	ptrExpr string,
	elem types.Type,
	resetIface *types.Interface,
	typeQual func(*types.Package) string,
) []string {
	if types.Implements(elem, resetIface) {
		return []string{fmt.Sprintf("(*%s).Reset()", ptrExpr)}
	}
	if types.Implements(types.NewPointer(elem), resetIface) {
		return []string{fmt.Sprintf("(&(*%s)).Reset()", ptrExpr)}
	}

	switch elem.(type) {
	case *types.Slice:
		return []string{fmt.Sprintf("*%s = (*%s)[:0]", ptrExpr, ptrExpr)}
	case *types.Map:
		return []string{fmt.Sprintf("clear(*%s)", ptrExpr)}
	}

	z := zeroValueExpr(elem, typeQual)
	if z == "" {
		return nil
	}
	return []string{fmt.Sprintf("*%s = %s", ptrExpr, z)}
}

func zeroValueExpr(t types.Type, typeQual func(*types.Package) string) string {
	switch tt := t.(type) {
	case *types.Basic:
		switch tt.Kind() {
		case types.Bool:
			return "false"
		case types.String:
			return `""`
		case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
			types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr,
			types.Float32, types.Float64,
			types.Complex64, types.Complex128:
			return "0"
		default:
			return "nil"
		}

	case *types.Named:
		under := tt.Underlying()
		typeStr := types.TypeString(tt, typeQual)

		if ub, ok := under.(*types.Basic); ok {
			z := zeroValueExpr(ub, typeQual)
			if z == "" {
				return ""
			}
			return fmt.Sprintf("%s(%s)", typeStr, z)
		}
		if _, ok := under.(*types.Struct); ok {
			return typeStr + "{}"
		}
		return "nil"

	case *types.Struct:
		return types.TypeString(tt, typeQual) + "{}"

	case *types.Pointer, *types.Interface, *types.Signature, *types.Chan, *types.Slice, *types.Map:
		return "nil"

	case *types.Array:
		return types.TypeString(tt, typeQual) + "{}"

	default:
		return "nil"
	}
}

func ensureImport(imports map[string]string, used map[string]bool, path, suggested string) string {
	if alias, ok := imports[path]; ok {
		if alias == "" {
			return suggested
		}
		return alias
	}

	alias := suggested
	if alias == "" {
		alias = sanitizeIdent(filepath.Base(path))
	} else {
		alias = sanitizeIdent(alias)
	}

	if used[alias] {
		base := alias
		for i := 2; ; i++ {
			try := fmt.Sprintf("%s%d", base, i)
			if !used[try] {
				alias = try
				break
			}
		}
	}
	used[alias] = true

	if alias == sanitizeIdent(suggested) {
		imports[path] = ""
		return suggested
	}

	imports[path] = alias
	return alias
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		ok := (r >= 'a' && r <= 'z') ||
			(r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') ||
			r == '_'
		if !ok {
			r = '_'
		}
		if i == 0 && r >= '0' && r <= '9' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	if b.Len() == 0 {
		return "pkg"
	}
	return b.String()
}
